// THIS FILE IS MANAGED BY AUTOMATED CODE GENERATION. See: codegen.go
package loader

import (
	_ "github.com/davejhilton/adventofcode/challenges/2020/day01"
	_ "github.com/davejhilton/adventofcode/challenges/2020/day02"
	_ "github.com/davejhilton/adventofcode/challenges/2020/day03"
	_ "github.com/davejhilton/adventofcode/challenges/2020/day04"
	_ "github.com/davejhilton/adventofcode/challenges/2020/day05"
	_ "github.com/davejhilton/adventofcode/challenges/2020/day06"
	_ "github.com/davejhilton/adventofcode/challenges/2020/day07"
	_ "github.com/davejhilton/adventofcode/challenges/2020/day08"
	_ "github.com/davejhilton/adventofcode/challenges/2020/day09"
	_ "github.com/davejhilton/adventofcode/challenges/2020/day10"
	_ "github.com/davejhilton/adventofcode/challenges/2020/day11"
	_ "github.com/davejhilton/adventofcode/challenges/2020/day12"
	_ "github.com/davejhilton/adventofcode/challenges/2020/day13"
	_ "github.com/davejhilton/adventofcode/challenges/2020/day14"
	_ "github.com/davejhilton/adventofcode/challenges/2020/day15"
	_ "github.com/davejhilton/adventofcode/challenges/2020/day16"
	_ "github.com/davejhilton/adventofcode/challenges/2020/day17"
	_ "github.com/davejhilton/adventofcode/challenges/2020/day18"
	_ "github.com/davejhilton/adventofcode/challenges/2020/day19"
	_ "github.com/davejhilton/adventofcode/challenges/2020/day20"
	_ "github.com/davejhilton/adventofcode/challenges/2020/day21"
	_ "github.com/davejhilton/adventofcode/challenges/2020/day22"
	_ "github.com/davejhilton/adventofcode/challenges/2020/day23"
	_ "github.com/davejhilton/adventofcode/challenges/2020/day24"
	_ "github.com/davejhilton/adventofcode/challenges/2020/day25"

	_ "github.com/davejhilton/adventofcode/challenges/2021/day01"
	_ "github.com/davejhilton/adventofcode/challenges/2021/day02"
	_ "github.com/davejhilton/adventofcode/challenges/2021/day03"
	_ "github.com/davejhilton/adventofcode/challenges/2021/day04"
	_ "github.com/davejhilton/adventofcode/challenges/2021/day05"
	_ "github.com/davejhilton/adventofcode/challenges/2021/day06"
	_ "github.com/davejhilton/adventofcode/challenges/2021/day07"
	_ "github.com/davejhilton/adventofcode/challenges/2021/day08"
	_ "github.com/davejhilton/adventofcode/challenges/2021/day09"
	_ "github.com/davejhilton/adventofcode/challenges/2021/day10"
	_ "github.com/davejhilton/adventofcode/challenges/2021/day11"
	_ "github.com/davejhilton/adventofcode/challenges/2021/day12"
	_ "github.com/davejhilton/adventofcode/challenges/2021/day13"
	_ "github.com/davejhilton/adventofcode/challenges/2021/day14"
	_ "github.com/davejhilton/adventofcode/challenges/2021/day15"
	_ "github.com/davejhilton/adventofcode/challenges/2021/day16"
	_ "github.com/davejhilton/adventofcode/challenges/2021/day17"
	_ "github.com/davejhilton/adventofcode/challenges/2021/day18"
	_ "github.com/davejhilton/adventofcode/challenges/2021/day19"
	_ "github.com/davejhilton/adventofcode/challenges/2021/day20"
	_ "github.com/davejhilton/adventofcode/challenges/2021/day21"
	_ "github.com/davejhilton/adventofcode/challenges/2021/day22"
	_ "github.com/davejhilton/adventofcode/challenges/2021/day23"
	_ "github.com/davejhilton/adventofcode/challenges/2021/day24"
	_ "github.com/davejhilton/adventofcode/challenges/2021/day25"

	_ "github.com/davejhilton/adventofcode/challenges/2022/day01"
	// CODEGEN: INSERT HERE
)
